### ISSUE TITLE
LURO improvements

### ISSUE THREAD

**Issue by bf-monster** [betfinio/luro#30]
- [x] Missing rectangles on Players and Bets tabs. We would like it as in Bonus tab

 ![Image](https://github.com/user-attachments/assets/564a78b1-d1dc-4ad7-ad26-da69df710ec8)
![Image](https://github.com/user-attachments/assets/9fb41546-0eb8-4c6d-a26a-12faacea27b0)
![Image](https://github.com/user-attachments/assets/99480ce8-0c18-4a24-92e3-3aed477f4f6c)

- [x] Add non transparent background

![Image](https://github.com/user-attachments/assets/811251d2-192d-465b-8c53-28b8d8bfc428)

- [x] Add non transparent background

![Image](https://github.com/user-attachments/assets/d5b4aa63-5d58-451c-8909-4bb0c4d624b5)

**Comment by bf-plane** [comment]
#31
